label chapter3_day2:
    scene black
    with fade
    centered "Day 2 - Tuesday 2nd January."
    pause 1.0

    scene bg bedroom day
    with fade
    "I open my eyes."
    "The sun is blinding. It takes a moment to adjust to the light."
    "I blink a few times, then sit up."
    "???" "Good morning."
    my "GAH-"
    show hareka arbiter normal
    "The girl is still sitting there."
    my "I forgot you were there... Jeez, you almost gave me a heart attack!"
    "???" "That is an exaggeration."
    my "Duh..."
    "I let out a yawn, stretching."
    show hareka arbiter eyes_closed normal
    "???" "Today is Tuesday 2nd January."
    "???" "Today's weather is 100\% rain all day."
    my "What-"
    my "Well, that's to be expected."
    my "I didn't ask for you to tell me that though..."
    "???" "I am simply giving you a morning briefing."
    "???" "Would you like to turn off this feature?"
    my "...Feature?"
    show hareka arbiter normal
    "???" "Would you like to turn off the morning briefing feature?"
    "She gives me that cold glare again."
    "I feel a shiver run down my spine."
    my "No, no..."
    my "You're acting like a robot, jeez..."
    "It's then that I remember what she said last night."
    "I gasp."
    my "Are you a robot?!"
    "???" "I am not a robot."
    my "Wh-"
    my "What are you, then?!"
    show hareka arbiter eyes_closed normal
    "???" "Loading model information..."
    show hareka arbiter normal
    "???" "I am RingAI Model 3 Interface. RAIM3I is the shorthand form."
    "???" "I am the leading innovation in artifical intelligence design. I was designed specifically for Arbiter work. I was designed to complete work efficiently and with minimal mess."
    "???" "I have been assigned to monitor you."
    "..."
    my "Wow..."
    my "You're really an AI..."
    "???" "I have been assigned a human name."
    my "Oh?"
    my "What is it?"
    hareka "My human name is Hareka."
    my "Oh."
    my "That's a nice name..."
    hareka "Thank you."
    my "Well then..."
    my "This explains a lot, I suppose."
    hareka "Are you satisfied with the information I provided?"
    my "Yep."
    show hareka arbiter eyes_closed normal
    hareka "Good."
    show hareka arbiter normal
    hareka "It is time for you to eat. Follow me."
    my "Oh right... Okay."

    scene bg kitchen day
    with fade
    show hareka arbiter normal
    with moveinright
    "We enter the kitchen."
    hareka "Sit down."
    my "Okay..."
    "I sit down at the counter."
    "She begins making me some buttered toast."
    my "The day is gonna be boring without work..."
    my "What am I even meant to do if I'm not allowed to go outside?"
    hareka "There are plenty of indoor activities to keep you satisfied."
    hareka "Have you ever tried chess? It's a strategic game, and as such takes up a lot of time."
    my "Eh..."
    my "I'm not really into that sorta stuff..."
    hareka "There are more tasks."
    hareka "You could always do chores, or studying, if you'd prefer."
    my "..."
    my "No thanks..."
    show hareka arbiter eyes_closed normal
    hareka "Humans are so troublesome..."
    show hareka arbiter normal
    hareka "Here is your food."
    "She hands me the toast."
    my "Thanks..."
    my "Do you have to eat, Hareka?"
    hareka "I do not need nutrition to function. I do have the ability to digest food, but it is not a necessity."
    show hareka arbiter eyes_closed normal
    hareka "Even if I did eat, I do not have the sense of taste required to enjoy it..."
    my "Oh... How sad..."
    show hareka arbiter normal
    hareka "I am not sad about it."
    hareka "I am designed with optimal functionality in mind. It would not be good for me to get hungry or tired midjob, would it?"
    my "I suppose not..."
    my "I mean, it makes sense, at least."
    hareka "Good. I'm glad you understand."
    hareka "Now, eat."
    my "Okay."
    "I eat the toast."
    "It's soft, just the way I like it..."
    "I remember someone making it that way before..."

    scene bg kitchen day
    show vignette zorder 3
    show mora arbiter no_coat normal
    with flash
    mora "Is buttered toast okay?"
    my "Yeah. Not too burnt. Thank you."
    "She gets out some bread, and pops it into the toaster."
    "She prepares the butter and plate ready."
    "I wait patiently."
    "Once the toast pops up, she butters it evenly."
    "She hands me the plate, and also a glass of water."
    mora "Hydration is important."
    my "Thank you."
    "..."
    "I take a bite of the toast."
    "It's soft, just the way I like it. I don't really like burnt toast."
    my "This is yummy."
    mora "Good."
    "We eat in silence."
    "..."

    scene bg kitchen day
    show hareka arbiter eyes_closed normal
    with flash
    hareka "..."
    hareka "This isn't good."
    show hareka arbiter normal
    hareka "Are you okay?"
    my "Huh-"
    "I blink a few times."
    hareka "You were spaced out."
    my "Oh..."
    my "Yeah, I'm fine."
    hareka "Good."
    "I finish the food."
    my "Thank you..."
    hareka "There's no need to thank me."
    hareka "I'll put the plates in the dishwasher. Wait there for a moment."
    "She carefully places the plates in the dishwasher."
    "I notice how wary she is."
    "I wonder..."
    hareka "All done."
    hareka "Where would you like to go now? Inside the house, of course."
    my "I need to take a bath."
    hareka "Very well. Follow me."

    scene bg bathroom
    show hareka arbiter normal
    with fade
    "We enter the bathroom."
    "I begin to get undressed."
    "I am a bit embarrassed, but really, she's only an AI, so as long as she doesn't have some recording feature, it's fine..."
    "I fill the bathtub up with water."
    scene bg bathroom foggy
    show hareka arbiter normal
    with fade
    my "Okay, ready."
    "I get in the bath."
    "It's nice and warm."
    "I take a few minutes to enjoy it."
    "Okay, time to test my theory..."
    "I'm sorry, Hareka..."
    my "Hey, Hareka, can you come here a sec? I need some help."
    hareka "Okay."
    "She just obliges..."
    "Does she have no danger awareness???"
    hareka "What do you need help with?"
    my "I need you to grab the shampoo for me. I can't reach."
    hareka "Okay."
    show hareka arbiter eyes_closed normal
    "She reaches up to grab it."
    "I take this opportunity to grab her torso, pulling her down with force."
    "She lands in the water with a soft splash."
    "Only her upper half is submerged. Her legs are left dangling in the air."
    "It's a bit of an awkward position... I hope she can't feel pain..."
    show hareka arbiter corrupted
    with hpunch
    "She pulls herself up."
    "She's convulsing, and for some reason, one of her eyes is red."
    hareka "Error... Moisture detected..."
    hareka "Error... Error..."
    "My theory was right."
    my "Hareka, you need to be careful when you pick targets."
    my "I'm smarter than people think."
    hareka "Error..."
    hareka "Sending out distress signal..."
    my "WHAT-"
    "She stands up."
    hareka "Distress signal sent."
    hareka "An Arbiter has been sent to the current location."
    my "Shit..."
    hide hareka
    with vpunch
    "Hareka collapses, falling out of the bath onto the floor."
    "I give her a worried glance."
    "She really did break..."
    "But if there's a distress signal..."
    "I didn't know about that..."
    "I'm in deep shit now."
    "A crash comes from the other room."
    "???" "Hareka?!"
    "I freeze, unsure what to do."
    "Then I realise."
    "I know what I have to do."
    "I have to lie."
    my "She's in here!"
    "I call out to the person."
    show amita star eyes_closed sad with moveinright
    "A girl enters."
    "She immediately grabs Hareka from the floor."
    "???" "Oh Hareka..."
    my "Uhm..."
    my "She fell into the bath when reaching up, so I tried pulling her out, but it was too late..."
    "I lie."
    "???" "Oh, it's okay. This happens a lot."
    "She begins working on fixing Hareka."
    "There's a lot of tools I've never seen before."
    "She works swiftly."
    "???" "You should get dressed."
    my "AH-"
    "I completely forgot I was naked..."
    "I hurriedly grab a towel and wrap it around me."
    my "I'm sorry..."
    "???" "There's no need to apologise."
    "She continues working."
    "I dry off and get dressed."
    "{b}{u}15 minutes later...{/u}{/b}"
    "???" "There we go."
    my "Is it done?"
    "???" "Should be... We'll have to see."
    "I've had to wait for a while, since I can't be unattended..."
    "She disconnects her equipment."
    "Hareka begins to wake up."
    "I sigh in relief."
    show hareka arbiter corrupted at left
    show amita at right
    hareka "Error. Moisture detected."
    "???" "Sigh."
    "???" "External or internal?"
    hareka "External moisture detected."
    my "Oh, does it mean her clothes?"
    "???" "Probably."
    "???" "I'll get her changed. Mind looking away for a sec?"
    my "Eh... Okay then."
    hide hareka
    hide amita
    "I turn away."
    "???" "I should have some spare clothes in here somewhere..."
    "???" "Hm..."
    "Some shuffling."
    "???" "Oh! Found it!"
    "More shuffling."
    "I wait impatiently."
    "???" "Done!"
    "???" "You can turn back around now."
    show hareka casual normal at left
    show amita star eyes_closed normal at right
    "I turn around."
    "It feels weird seeing her in a new outfit for some reason..."
    "???" "Yay! The error code is gone!"
    my "Error code?"
    my "She didn't say anything..."
    "???" "Her red eye meant an error."
    "???" "It's gone now, so I did my job right!"
    my "Oh, I see..."
    "???" "Hareka, perform internal checkup."
    hareka "There are no internal issues."
    "???" "Good!"
    my "Do you... remember what happened?"
    hareka "Did something happen?"
    my "I guess not then..."
    "???" "A safeguarding feature. Erases her memory of a few minutes before the incident."
    my "Oh."
    my "That's good then."
    "???" "Ehehe."
    my "Anyways uhm..."
    my "Are you really an Arbiter? You don't look like one..."
    "???" "I get that a lot."
    "???" "I'd usually be in my uniform, but I was called so suddenly, so I didn't have time..."
    my "Yeah, you sure did get here fast..."
    "???" "The distress signal goes to the nearest person!"
    "???" "That just happened to be me!"
    my "Who are you, anyways?"
    "???" "Oh, oops! How rude of me!"
    show amita star normal
    amita "My name is Amita!"
    "!!!"
    "Her eyes..."
    "They're so sparkly..."
    "Her expression is so bright..."
    "She shines... Like a star..."
    my "Nice to meet you..."
    my "You're unlike any Arbiter I've seen..."
    amita "I get that a lot, too~!"
    amita "I guess you could say I'm the most human of us!"
    hareka "Amita has hope left inside of her."
    hareka "Most of the human Arbiters had their hopes crushed, and I never had any to begin with, as I do not have a soul."
    my "Oh..."
    my "That's so sad..."
    amita "I just know everything will be fine, you know?"
    amita "Any situation can be fixed!"
    my "That's an admirable mindset."
    hareka "Your job is done now, Amita. You should leave."
    hareka "Our job is not to converse with captors that are not ours."
    amita "Aw... Okay, miss!"
    amita "Goodbye, Alex!"
    my "Goodbye..."
    hide amita with moveoutright
    show hareka at center
    "She leaves."
    "I'm left with a warm feeling."
    "Her smile... It's so genuine..."
    hareka "Do not get entranced by her."
    hareka "She is not to be trusted. None of us can be trusted."
    hareka "Our job is to bring down enemies."
    my "I'm an enemy?"
    hareka "Perhaps. We are still collecting information on you."
    hareka "Did you enjoy your bath?"
    my "...Yeah. It was good."
    "I'd better not let her find out what happened..."
    hareka "Good. Let's go into the bedroom."
    my "Okay..."

    scene bg bedroom day
    show hareka casual normal
    with fade
    "We enter the bedroom."
    hareka "I need to do work here."
    hareka "There are books you can read, or a couple of games."
    hareka "You can also nap, if you'd like."
    my "Oh, thank you..."
    my "Aren't you supposed to watch me though?"
    my "How would you do work?"
    hareka "I will still be watching from the corner of my vision."
    hareka "Do not try anything. I am always watching."
    my "Ah... Okay..."
    "She's scary."
    "She sits down at the desk, grabbing a laptop and booting it up."
    "I grab a book and sit on the bed."
    "Guess I should read a bit..."
    "{b}{u}An hour later...{/u}{/b}"
    hareka "It's time for lunch."
    my "Oh."
    "I'd been completely absorbed in the book..."
    
    scene bg kitchen day
    show hareka casual normal
    with fade
    "We head into the kitchen."
    "I sit down and she prepares a sandwich."
    my "Thank you."
    hareka "Nutrition is important, for you."
    my "True..."
    "I'll admit, I haven't really been eating properly, for a while now..."
    "Maybe I'll be looked after here. I could get healthier..."
    "She passes me a glass of water and the sandwich."
    hareka "Hydration is just as important."
    my "Yep."
    my "I'm sure I was told that before..."
    hareka "It is common knowledge."
    my "That's true."
    "I eat."
    "It's cheese filled. My favourite..."
    "I love cheese. How did she know?"
    "Just how much info does the government have on me...?"
    "I quickly finish the sandwich."
    "She grabs the plate."
    my "Oh wait, I'll put it in the dishwasher!"
    hareka "Why?"
    my "Uh... It's only a small plate so I don't mind..."
    "I almost got caught there."
    hareka "Fine."
    "She gives me the plate."
    "I put it in the dishwasher, carefully."
    "Why do I care {i}more{/i} about her now I know her weakness?!"
    "Gosh..."
    hareka "Let's return to the bedroom."
    my "Okay."

    scene bg bedroom evening
    show hareka casual normal
    with fade
    hareka "I shall continue with my work."
    my "Okay, I'll continue reading."
    "We each do our activities."
    "{b}{u}A few hours later...{/u}{/b}"
    "I finish the book."
    "It was a nice romance story."
    hareka "It is time for dinner."
    my "Oh, right, okay."
    "I put the book away."

    scene bg kitchen day
    show hareka casual normal
    with fade
    "We enter the kitchen again."
    hareka "I will make some noodles for you."
    my "Ah... Thank you. I like noodles."
    hareka "That's good."
    "She grabs an instant noodles pot from the cupboard."
    hareka "Usually I would cook a better dinner."
    my "You must be tired from maintenance."
    show hareka casual eyes_closed normal
    hareka "I've already told you, I don't get tired."
    my "Oh right... Sorry."
    show hareka casual normal
    hareka "It's fine."
    "She glances over the instructions."
    my "Want me to help?"
    hareka "You don't have to."
    hareka "It's part of my job to look after you while you're here."
    my "That may be true, but there's nothing wrong with getting help sometimes, you know?"
    my "I feel a bit useless, to be honest, without a job."
    hareka "Oh."
    hareka "If you want to, fine."
    hareka "Can you put the kettle on? The instructions say I need hot water."
    my "Okay!"
    "I grab the kettle and fill it up, then flick the stand. It begins heating up."
    "While we wait for it to boil, she opens the pot, and takes out the sauce sachet."
    "I get a fork out of the drawer."
    "The kettle finishes boiling, and I pour it into the pot. She begins stirring."
    "After a while, it's time to add the sauce. I open the sachet and pour it in. She continues stirring."
    "After a bit more stirring, the noodles are ready."
    "She hands me the pot."
    hareka "Here you go."
    my "Thank you!"
    "I sit down at the counter."
    "She stands and watches as I eat the noodles."
    my "It's nice..."
    hareka "Good."
    "{b}{u}A few minutes later...{/u}{/b}"
    "I finish the noodles."
    "The pot goes in the recycling bin, and I put the fork in the dishwasher."
    my "That was great, thanks!"
    hareka "There's no need to thank me."
    hareka "It's getting late now. You should get to bed."
    my "Ah yeah... Good idea, I'm getting tired now..."
    hareka "Let's go then."
    my "Okay."

    scene bg bedroom night
    show hareka casual normal
    with fade
    hareka "I will continue my work."
    my "Oki..."
    "I get into bed, exhausted."
    my "Good night, Hareka..."
    show hareka casual eyes_closed normal
    hareka "Good night."
    window hide
    $ chapter3_day3_avail = True
    scene black
    with fade
    centered "End of day."
    menu chapter3_day2_end:
        "Day 2 (Chapter 3 - Day 2) complete!"
        "Would you like to return to the chapter selection screen, or carry onto the next day?"
        "Chapter selection.":
            jump chapter_select
        "Carry on.":
            jump chapter3_day3